---
title: "Summary statistics"
output: md_document
params:
    stats_list: NA
    dist_select: NA
    country_select: NA
always_allow_html: yes
geometry: "left = 3cm, right = 3cm, top = 2cm, bottom = 2cm"
---

```{r load_packages, echo = FALSE}

require(kableExtra)
require(knitr)
require(RColorBrewer)
require(plotfunctions)
require(sf)

country_select <- params$country_select
dist_select <- params$dist_select

dist_names <- unique(dist_select$NAME)

# create a lookup table for the variable names
var_name_orig <- c("A global friction surface enumerating land based travel speed for a nominal year 2015",
                   "A global map of travel time to cities to assess inequalities in accessibility in 2015",
                   "All cause fever",                                                                      
                   "Artemisinin based combination therapy  ACT  coverage",                                 
                   "Dominant Vectors",                                                                     
                   "Duffy Negativity Phenotype Frequency",                                                 
                   "G6PD Deficiency Allele Frequency",                                                     
                   "HbS  Sickle Haemoglobin  Allele Frequency",                                            
                   "Indoor residual spraying  IRS  coverage",                                              
                   "Insecticide treated bednet  ITN  coverage",                                            
                   "Malaria attributable fever as a proportion of all cause fever",                        
                   "Malaria attributable fever as a proportion of malaria positive fever",                 
                   "Malaria positive fever as a proportion of all cause fever",                            
                   "Non malarial fever",                                                                   
                   "Plasmodium falciparum Incidence",                                                      
                   "Plasmodium falciparum PR2 10",                                                         
                   "Plasmodium falciparum Spatial Limits",                                                 
                   "Plasmodium falciparum Support",                                                        
                   "Plasmodium falciparum Temperature Suitability",                                        
                   "Plasmodium knowlesi Risk",                                                             
                   "Plasmodium vivax Endemicity",                                                          
                   "Plasmodium vivax Relapse",                                                             
                   "Plasmodium vivax Spatial Limits",                                                      
                   "Plasmodium vivax Support",                                                             
                   "Plasmodium vivax Temperature Suitability",                                             
                   "Secondary Dominant Vectors")

var_name_new <- c("Global friction surface (2015)",
                  "Global accessibility (2015)",
                  "All cause fever",                                                                      
                  "ACT coverage",                                 
                  "Dominant Vectors",                                                                     
                  "Duffy Negativity",                                                 
                  "G6PD Deficiency",                                                     
                  "HbS Sickle",                                            
                  "IRS coverage",                                              
                  "ITN coverage",                                            
                  "Malaria attributable fever (prop ACF)",                        
                  "Malaria attributable fever (prop malaria +ve fever)",                 
                  "Malaria positive fever (proportion ACF)",                            
                  "Non malarial fever",                                                                   
                  "Plasmodium falciparum Incidence",                                                      
                  "Plasmodium falciparum PR2 10",                                                         
                  "Plasmodium falciparum Spatial Limits",                                                 
                  "Plasmodium falciparum Support",                                                        
                  "Plasmodium falciparum temp. suitability",                                        
                  "Plasmodium knowlesi Risk",                                                             
                  "Plasmodium vivax Endemicity",                                                          
                  "Plasmodium vivax Relapse",                                                             
                  "Plasmodium vivax Spatial Limits",                                                      
                  "Plasmodium vivax Support",                                                             
                  "Plasmodium vivax temp. suitability",                                             
                  "Secondary Dominant Vectors")

var_name_units <- c("Land-based travel speed (minutes)",
                    "Time to travel to the nearest city (minutes)",
                    "All-cause fever prevalence within the limits of stable Pf \ntransmission, in children under 5 years of age", 
                    "Percentage of cases of fever in under-5 year olds that were \ntreated with ACT",                                 
                    "Probability (0-1)",                                                                     
                    "Proportion of the population predicted to be Duffy negative",                                                 
                    "Allele frequency (median) for G6PD deficiency",                                                     
                    "Allele frequency (mean) of sickle haemoglobin alleles",                                            
                    "Percentage of the population protected by IRS",                                              
                    "Proportion of the population who were protected by ITNs",                                            
                    "Predicted malaria attributable fevers (MAF) as a proportion \nof all fevers, for children under 5",                        
                    "Predicted malaria attributable fevers as a proportion of \nmalaria positive fevers, for children under 5",                 
                    "Predicted malaria-positive fevers as a proportion of all \nfevers, for children under 5",                            
                    "Non-malarial fever prevalence is defined as the sum of the \nprevalence of febrile illness without a P. falciparum malaria \ninfection and the prevalence of febrile illness coincident \nwith, but not caused by, a P. falciparum malaria infection, \nfor children under 5", 
                    "All-age incidence rate (clinical cases per 1,000 population \nper annum) of Plasmodium falciparum malaria",
                    "Age-standardised parasite rate for Plasmodium falciparum \nmalaria for children two to ten years of age (PfPR2-10)",
                    "Plasmodium falciparum Spatial Limits",                                                 
                    "Number of days per year which could support infectious \nvectors",                                                        
                    "The index of suitability is a relative, not absolute, \nmeasure of the effect of temperature on vectorial capacity \nand reproductive number",
                    "Modelled relative risk of zoonotic Plasmodium knowlesi \ninfecting humans on a scale 0 (low) to 1.0 (high)",
                    "Predicted all-age parasite prevalence rate for Plasmodium \nvivax malaria",                                                          
                    "Predicted prevalence of Plasmodium vivax relapse",                                                             
                    "Plasmodium vivax Spatial Limits",                                                      
                    "Number of days per year which could support infectious \nvectors",                                                             
                    "The index of suitability is a relative, not absolute, measure \nof the effect of temperature on vectorial capacity \nand reproductive number",
                    "Secondary Dominant Vectors")

var_lookup <- data.frame(original = var_name_orig,
                         new = var_name_new,
                         units = var_name_units)

```

```{r caption_css, results = "asis", echo = FALSE}
cat("
<style>
caption {
      color: #0dc5c1;
      font-weight: bold;
      font-size: 1.20em;
    }
</style>
")

```

## MAP-district-comparison Output Report
#### This document contains summary statistics for `r country_select$name`, and the following selected districts: `r dist_names`. 

#### Summary statistics for each selected variable appear below, and were generated using the "zonal" function within the "raster" R package.

</br>

```{r pop_stat_1, results = "axis", echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

stats_list <- params$stats_list

dist_select <- params$dist_select

# subset to get specified table
table_one <- stats_list[[1]]

# get variable names
variable_n <- names(table_one)[2]
variable_n <- substr(variable_n, 1, nchar(variable_n)-7)

# get units and shorter variable name
idx <- which(variable_n == var_lookup$original)
units_n <- as.character(var_lookup$units[idx])
variable_trim_n <- as.character(var_lookup$new[idx])

names(table_one) <- c("District",
                      "Mean",
                      "Max",
                      "Min",
                      "Standard Deviation")

# round so that values aren't ridiculously long
table_one$Mean <- round(table_one$Mean, 2)
table_one$Max <- round(table_one$Max, 2)
table_one$Min <- round(table_one$Min, 2)
table_one$`Standard Deviation` <- round(table_one$`Standard Deviation`, 2)

# replace negative values as NA
table_one$Mean[table_one$Mean < 0] <- NA
table_one$Max[table_one$Max < 0] <- NA
table_one$Min[table_one$Min < 0] <- NA
table_one$`Standard Deviation`[table_one$`Standard Deviation` < 0] <- NA

table_one$Mean[!complete.cases(table_one)] <- NA
table_one$Max[!complete.cases(table_one)] <- NA
table_one$Min[!complete.cases(table_one)] <- NA
table_one$`Standard Deviation`[!complete.cases(table_one)] <- NA

kable(table_one,
      row.names = FALSE,
      caption = variable_n,
      align = "c") %>% 
      add_footnote(label = units_n) %>%
      kable_styling(c("striped", "bordered")) %>% 
      column_spec(1, bold = TRUE, width = "7em") %>%
      column_spec(2:5, width = "5em") %>%
      kable_styling(full_width = FALSE,
                    position = "left")

```

</br>

```{r pop_stats_2, results = "axis", echo = FALSE}
if(length(stats_list) > 1){

# subset to get specified table
table_two <- stats_list[[2]]

# get variable names
variable_n2 <- names(table_two)[2]
variable_n2 <- substr(variable_n2, 1, nchar(variable_n2)-7)

# get units and shorter variable name
idx <- which(variable_n2 == var_lookup$original)
units_n2 <- as.character(var_lookup$units[idx])
variable_trim_n2 <- as.character(var_lookup$new[idx])

names(table_two) <- c("District",
                      "Mean",
                      "Max",
                      "Min",
                      "Standard Deviation")

# round so that values aren't ridiculously long
table_two$Mean <- round(table_two$Mean, 2)
table_two$Max <- round(table_two$Max, 2)
table_two$Min <- round(table_two$Min, 2)
table_two$`Standard Deviation` <- round(table_two$`Standard Deviation`, 2)

# replace negative values as NA
table_two$Mean[table_two$Mean < 0] <- NA
table_two$Max[table_two$Max < 0] <- NA
table_two$Min[table_two$Min < 0] <- NA
table_two$`Standard Deviation`[table_two$`Standard Deviation` < 0] <- NA

table_two$Mean[!complete.cases(table_two)] <- NA
table_two$Max[!complete.cases(table_two)] <- NA
table_two$Min[!complete.cases(table_two)] <- NA
table_two$`Standard Deviation`[!complete.cases(table_two)] <- NA

kable(table_two,
      row.names = FALSE,
      caption = variable_n2,
      align = "c") %>% 
      add_footnote(label = units_n2) %>%
      kable_styling(c("striped", "bordered")) %>% 
      column_spec(1, bold = TRUE, width = "7em") %>%
      column_spec(2:5, width = "5em") %>%
      kable_styling(full_width = FALSE,
                    position = "left")

}

```

</br>

```{r pop_stats_3, results = "axis", echo = FALSE}
if(length(stats_list) > 2){

# subset to get specified table
table_three <- stats_list[[3]]

# get variable names
variable_n3 <- names(table_three)[2]
variable_n3 <- substr(variable_n3, 1, nchar(variable_n3)-7)

# get units and shorter variable name
idx <- which(variable_n3 == var_lookup$original)
units_n3 <- as.character(var_lookup$units[idx])
variable_trim_n3 <- as.character(var_lookup$new[idx])

names(table_three) <- c("District",
                      "Mean",
                      "Max",
                      "Min",
                      "Standard Deviation")

# round so that values aren't ridiculously long
table_three$Mean <- round(table_three$Mean, 2)
table_three$Max <- round(table_three$Max, 2)
table_three$Min <- round(table_three$Min, 2)
table_three$`Standard Deviation` <- round(table_three$`Standard Deviation`, 2)

# replace negative values as NA
table_three$Mean[table_three$Mean < 0] <- NA
table_three$Max[table_three$Max < 0] <- NA
table_three$Min[table_three$Min < 0] <- NA
table_three$`Standard Deviation`[table_three$`Standard Deviation` < 0] <- NA

table_three$Mean[!complete.cases(table_three)] <- NA
table_three$Max[!complete.cases(table_three)] <- NA
table_three$Min[!complete.cases(table_three)] <- NA
table_three$`Standard Deviation`[!complete.cases(table_three)] <- NA

kable(table_three,
      row.names = FALSE,
      caption = variable_n3,
      align = "c") %>% 
      add_footnote(label = units_n3) %>%
      kable_styling(c("striped", "bordered")) %>% 
      column_spec(1, bold = TRUE, width = "7em") %>%
      column_spec(2:5, width = "5em") %>%
      kable_styling(full_width = FALSE,
                    position = "left")
  
}
```

</br>

```{r pop_stats_4, results = "axis", echo = FALSE}
if(length(stats_list) > 3){

# subset to get specified table
table_four <- stats_list[[4]]

# get variable names
variable_n4 <- names(table_four)[2]
variable_n4 <- substr(variable_n4, 1, nchar(variable_n4)-7)

# get units and shorter variable name
idx <- which(variable_n4 == var_lookup$original)
units_n4 <- as.character(var_lookup$units[idx])
variable_trim_n4 <- as.character(var_lookup$new[idx])

names(table_four) <- c("District",
                      "Mean",
                      "Max",
                      "Min",
                      "Standard Deviation")

# round so that values aren't ridiculously long
table_four$Mean <- round(table_four$Mean, 2)
table_four$Max <- round(table_four$Max, 2)
table_four$Min <- round(table_four$Min, 2)
table_four$`Standard Deviation` <- round(table_four$`Standard Deviation`, 2)

# replace negative values as NA
table_four$Mean[table_four$Mean < 0] <- NA
table_four$Max[table_four$Max < 0] <- NA
table_four$Min[table_four$Min < 0] <- NA
table_four$`Standard Deviation`[table_four$`Standard Deviation` < 0] <- NA

table_four$Mean[!complete.cases(table_four)] <- NA
table_four$Max[!complete.cases(table_four)] <- NA
table_four$Min[!complete.cases(table_four)] <- NA
table_four$`Standard Deviation`[!complete.cases(table_four)] <- NA

kable(table_four,
      row.names = FALSE,
      caption = variable_n4,
      align = "c") %>% 
      add_footnote(label = units_n4) %>%
      kable_styling(c("striped", "bordered")) %>% 
      column_spec(1, bold = TRUE, width = "7em") %>%
      column_spec(2:5, width = "5em") %>%
      kable_styling(full_width = FALSE,
                    position = "left")

}
```

```{r stat_plots, echo = FALSE, results = "hide", fig.height = 10, fig.width = 10}
# generate shapefile for the plot
if(length(stats_list) == 1){
  
  # first create an index
  dist_index <- match(dist_select$name, table_one$District)
  dist_select_v1 <- dist_select
  dist_select_v1$mean <- table_one$Mean[dist_index]
  
  # create a bespoke palette
  colour_p_v1 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select$mean))
  dist_select_v1$colours <- colour_p_v1[as.numeric(cut(dist_select_v1$mean, breaks = (length(dist_select_v1$mean))))]

  country_select <- params$country_select
  
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v1),
           col = dist_select_v1$colours,
           lty = 3,
           add = TRUE)
  
  title(variable_trim_n, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0.5)
  
  gradientLegend(valRange = c(min(dist_select_v1$mean, na.rm = TRUE), max(dist_select_v1$mean, na.rm = TRUE)), 
                 color = colour_p_v1, 
                 nCol = length(dist_select_v1$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)

  }

if(length(stats_list) == 2){
  
  dist_index <- match(dist_select$name, table_one$District)
  
  dist_select_v1 <- dist_select
  dist_select_v2 <- dist_select
  dist_select_v1$mean <- table_one$Mean[dist_index]
  dist_select_v2$mean <- table_two$Mean[dist_index]
  
  # create a bespoke palette
  colour_p_v1 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v1$mean))
  colour_p_v2 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v2$mean))
  dist_select_v1$colours <- colour_p_v1[as.numeric(cut(dist_select_v1$mean, breaks = (length(dist_select_v1$mean))))]
  dist_select_v2$colours <- colour_p_v2[as.numeric(cut(dist_select_v2$mean, breaks = (length(dist_select_v2$mean))))]
  
  # define plotting parameters
  par(mfrow = c(1,2),
      mar = c(5,4,4,2))
  
  country_select <- params$country_select

  # plot first stat
  plot(sf::st_geometry(country_select),
             col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v1),
           col = dist_select_v1$colours,
           lty = 3,
           add = TRUE)
  
  title(variable_trim_n, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v1$mean, na.rm = TRUE), max(dist_select_v1$mean, na.rm = TRUE)), 
                 color = colour_p_v1, 
                 nCol = length(dist_select_v1$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  # plot second stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v2),
           col = dist_select_v2$colours,
           lty = 3,
           add = TRUE)

  title(variable_trim_n2, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v2$mean, na.rm = TRUE), max(dist_select_v2$mean, na.rm = TRUE)), 
                 color = colour_p_v2, 
                 nCol = length(dist_select_v2$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
}

if(length(stats_list) == 3){
  
  dist_index <- match(dist_select$name, table_one$District)
  
  dist_select_v1 <- dist_select
  dist_select_v2 <- dist_select
  dist_select_v3 <- dist_select
  dist_select_v1$mean <- table_one$Mean[dist_index]
  dist_select_v2$mean <- table_two$Mean[dist_index]
  dist_select_v3$mean <- table_three$Mean[dist_index]
  
  # create a bespoke palette
  colour_p_v1 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v1$mean))
  colour_p_v2 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v2$mean))
  colour_p_v3 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v3$mean))
  dist_select_v1$colours <- colour_p_v1[as.numeric(cut(dist_select_v1$mean, breaks = (length(dist_select_v1$mean))))]
  dist_select_v2$colours <- colour_p_v2[as.numeric(cut(dist_select_v2$mean, breaks = (length(dist_select_v2$mean))))]
  dist_select_v3$colours <- colour_p_v3[as.numeric(cut(dist_select_v3$mean, breaks = (length(dist_select_v3$mean))))]
  
  # define plotting parameters
  par(mfrow = c(2,2),
      mar = c(5,4,4,2))
  
  country_select <- params$country_select

  # plot first stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v1),
           col = dist_select_v1$colours,
           lty = 3,
           add = TRUE)

  title(variable_trim_n, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v1$mean, na.rm = TRUE), max(dist_select_v1$mean, na.rm = TRUE)), 
                 color = colour_p_v1, 
                 nCol = length(dist_select_v1$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)

  # plot second stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v2),
           col = dist_select_v2$colours,
           lty = 3,
           add = TRUE)

  title(variable_trim_n2, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v2$mean, na.rm = TRUE), max(dist_select_v2$mean, na.rm = TRUE)), 
                 color = colour_p_v2, 
                 nCol = length(dist_select_v2$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  # plot third stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v3),
           col = dist_select_v3$colours,
           lty = 3,
           add = TRUE)
  
  title(variable_trim_n3, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v3$mean, na.rm = TRUE), max(dist_select_v3$mean, na.rm = TRUE)), 
                 color = colour_p_v3, 
                 nCol = length(dist_select_v3$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  }

if(length(stats_list) == 4){
  
  dist_index <- match(dist_select$name, table_one$District)
  
  dist_select_v1 <- dist_select
  dist_select_v2 <- dist_select
  dist_select_v3 <- dist_select
  dist_select_v4 <- dist_select
  dist_select_v1$mean <- table_one$Mean[dist_index]
  dist_select_v2$mean <- table_two$Mean[dist_index]
  dist_select_v3$mean <- table_three$Mean[dist_index]
  dist_select_v4$mean <- table_four$Mean[dist_index]
  
  # create a bespoke palette
  colour_p_v1 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v1$mean))
  colour_p_v2 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v2$mean))
  colour_p_v3 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v3$mean))
  colour_p_v4 <- colorRampPalette(brewer.pal(brewer.pal.info["YlGnBu",1], "YlGnBu"))(length(dist_select_v4$mean))
  dist_select_v1$colours <- colour_p_v1[as.numeric(cut(dist_select_v1$mean, breaks = (length(dist_select_v1$mean))))]
  dist_select_v2$colours <- colour_p_v2[as.numeric(cut(dist_select_v2$mean, breaks = (length(dist_select_v2$mean))))]
  dist_select_v3$colours <- colour_p_v3[as.numeric(cut(dist_select_v3$mean, breaks = (length(dist_select_v3$mean))))]
  dist_select_v4$colours <- colour_p_v4[as.numeric(cut(dist_select_v4$mean, breaks = (length(dist_select_v4$mean))))]
  
  # define plotting parameters
  par(mfrow = c(2,2),
      mar = c(5,4,4,2))
  
  country_select <- params$country_select

  # plot first stat
  print(plot(sf::st_geometry(country_select),
             col = "#d9d9d9"))
    
  plot(sf::st_geometry(dist_select_v1),
           col = dist_select_v1$colours,
           lty = 3,
           add = TRUE)
  
  title(variable_trim_n, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0.5)
  
  gradientLegend(valRange = c(min(dist_select_v1$mean, na.rm = TRUE), max(dist_select_v1$mean, na.rm = TRUE)), 
                 color = colour_p_v1, 
                 nCol = length(dist_select_v1$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)

  # plot second stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v2),
           col = dist_select_v2$colours,
           lty = 3,
           add = TRUE)

  title(variable_trim_n2, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v2$mean, na.rm = TRUE), max(dist_select_v2$mean, na.rm = TRUE)), 
                 color = colour_p_v2, 
                 nCol = length(dist_select_v2$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  # plot third stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v3),
           col = dist_select_v3$colours,
           lty = 3,
           add = TRUE)
  
  title(variable_trim_n3, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v3$mean, na.rm = TRUE), max(dist_select_v3$mean, na.rm = TRUE)), 
                 color = colour_p_v3, 
                 nCol = length(dist_select_v3$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  # plot fourth stat
  plot(sf::st_geometry(country_select),
           col = "#d9d9d9")
    
  plot(sf::st_geometry(dist_select_v4),
           col = dist_select_v4$colours,
           lty = 3,
           add = TRUE)

  title(variable_trim_n4, 
        cex.main = 1.2, col.main = "#0dc5c1",
        adj = 0)
  
  gradientLegend(valRange = c(min(dist_select_v4$mean, na.rm = TRUE), max(dist_select_v4$mean, na.rm = TRUE)), 
                 color = colour_p_v4, 
                 nCol = length(dist_select_v4$mean), 
                 pos = 0.5, 
                 side = 4,
                 length = 0.25, 
                 depth = 0.05, 
                 inside = TRUE, 
                 coords = FALSE,
                 pos.num = NULL, 
                 n.seg = 3, 
                 border.col = "black", 
                 dec = 2,
                 fit.margin = TRUE)
  
  }

```
